# Generated by Django 5.1 on 2024-08-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='note',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='DailyReport',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
